### ISSUE TITLE
Avoiding Rebuilding Widgets on tab change?

### ISSUE THREAD

**Issue by stickyburn** [eric-taix/fluid-nav-bar#11]
Hi devs! Thanks for such a delightful and easy to use bottom tab!
I'm making API calls using the provider library and using bottom tabs to separate the pages, however on each tab change my widgets are being rebuilt, resulting in my API calls being called multiple times. I'm not too sure if this is a flutter or provider related issue but any ideas if this is due to the bottom tab behavior ?

**Comment by eric-taix-teads** [comment]
Hey ✋ 
This is not related to this widget! When the page changes, your callback is called and you **manage** the page to show. So the issue in on your side ;-)
