### ISSUE TITLE
Respect safe area

### ISSUE THREAD

**Issue by cstsortan** [eric-taix/fluid-nav-bar#16]
Is there a way to make it add internal padding from the bottom to prevent icons overlapping with a bar like in iOS?

**Comment by eric-taix-teads** [comment]
`SafeArea` would do the trick for both iOS and Android. As it is a bottom bar we can set the `bottom` field to `true` and other attribute to `false`:
```dart
return SafeArea(
  child: FluidBottomNavBar(
    ...
  ),
  bottom: true,
  top: false,
  right: false,
  left: false,
);
```
I didn't add it to the widget because I think it's an application concern, but you can add a `SafeArea` if you care about.

**Comment by eric-taix** [comment]
Since there is no additional information, I close this problem. Do not hesitate to reopen it if necessary.
