### ISSUE TITLE
hi,What's the problem?

### ISSUE THREAD

**Issue by momtboy** [eric-taix/fluid-nav-bar#18]
`════════ Exception caught by SVG ═══════════════════════════════════════════════════════════════════
The following UnimplementedError was thrown in parseSvgElement:
The <style> element is not implemented in this library.

Style elements are not supported by this library and the requested SVG may not render as intended.

If possible, ensure the SVG uses inline styles and/or attributes (which are supported), or use a preprocessing utility such as svgcleaner to inline the styles for you.

Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#d997b(), name: "assets/navbar/home.svg", colorFilter: ColorFilter.mode(Color(0xffffffff), BlendMode.srcIn))`

**flutter sdk 1.20.1**

**Comment by eric-taix** [comment]
I think the explanation is understandable: the SVG you used has a `<style>` element which is not supported by the underlying library used by this widget. Try to use another SVG or use svgcleaner to inline the styles.
