### ISSUE TITLE
Can I display the label before touching?

### ISSUE THREAD

**Issue by mohammadmiiad** [eric-taix/fluid-nav-bar#19]
hello.
i want to show a label under the icon in menu navigation.
i read your document and i saw your example.
i ran your code on Github but i can't see any label for icon.
![Capture](https://user-images.githubusercontent.com/71085293/92750570-6f8a3e00-f39c-11ea-8e58-d28f0e4a0bdc.PNG)
i show you what i want on this picture!
![Captusaare](https://user-images.githubusercontent.com/71085293/92751330-1bcc2480-f39d-11ea-9b34-7f2c34190d34.jpg)
thank you for helping!

**Comment by eric-taix** [comment]
The example does not explain how to display a label, where did you read that?  
This is not possible to display a label for now.

**Comment by ChandraPrakashJangid** [comment]
@mohammadmiiad have you got any solution for this.

**Comment by eric-taix** [comment]
Sorry but today there's no way to add a label under the icon

**Comment by eric-taix** [comment]
Due to stale issue, I'm closing this issue. Feel free to re-open it if needed.
