### ISSUE TITLE
hello , there is a problem !  how to change here's color to transparent ??

### ISSUE THREAD

**Issue by bigfish258** [eric-taix/fluid-nav-bar#22]
![Snipaste_2020-10-15_00-30-26](https://user-images.githubusercontent.com/37959275/96018872-59c9d600-0e7e-11eb-97bd-6d1af6f0f6a4.png)

**Comment by eric-taix** [comment]
The background is transparent, it's probably due to your code. Try with the provided example or provide a sample which does not work please

**Comment by eric-taix** [comment]
Due to stale issue, I'm closing this issue. Feel free to re-open it if needed.

**Comment by JakesMD** [comment]
Just in case some people are still having trouble with this issue: I found it occurs when wrapping the body in a `SafeArea`. Setting `bottom: false` in the `SafeArea` does the trick. 

```dart
class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBody: true,
      body: SafeArea(
        bottom: false,
        child: _body,
      ),
      bottomNavigationBar: FluidNavBar(
        icons: [
          FluidNavBarIcon(icon: MdiIcons.home),
          FluidNavBarIcon(icon: MdiIcons.calendar)
          FluidNavBarIcon(icon: MdiIcons.cog),
        ],
      ),
    );
  }
}
```
