### ISSUE TITLE
Coudn't set specific duration

### ISSUE THREAD

**Issue by prateekmedia** [eric-taix/fluid-nav-bar#27]
When I set the duration in _handleNavigationBar function let's say 50 , but it is taking more time to complete its animation and the navigation bar is unclickable for that time span. I want the animation to be as quick as possible so that the bottom navigation bar is still clickable.

Can you provide another way of giving duration of the animation also can be please cross confirm the same..?

**Comment by eric-taix** [comment]
`_handleNavigationBar` in the example code is not to set the duration of the animation!
If you want to change the duration of the navigation bar 's animation, use the `animationFactor` field (see the documentation)
