### ISSUE TITLE
Animation doesn't work perfectly when stacked fluid-nav-bar with background image

### ISSUE THREAD

**Issue by vinay504** [eric-taix/fluid-nav-bar#36]
I have 5 icon buttons in fluid-nav-bar. first is homepage with image background stacked with other widgets and fluid-nav-bar. Issue is when i switch from home to other tabs animation does not work as it needs to be. But it works perfectly when there is no stack widget used.

**Comment by eric-taix** [comment]
Does this junk appears in production mode? And is your home page being rebuild during the transition between pages?
