### ISSUE TITLE
Got the following error when including the package

### ISSUE THREAD

**Issue by sarcastic-verma** [eric-taix/fluid-nav-bar#8]
Compiler message:
`
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:218:12: Error: Expected an identifier, but got '('.
  setState(() {
           ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:218:15: Error: Expected ')' before this.
  setState(() {
              ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:222:3: Error: A method declaration needs an explicit list of parameters.
Try adding a parameter list to the method declaration.
  _yController.value = 1.0;
  ^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:222:22: Error: Only factory constructor can specify '=' redirection.
Try making this a factory constructor, or remove the redirection.
  _yController.value = 1.0;
                     ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:222:24: Error: Expected an identifier, but got '1.0'.
  _yController.value = 1.0;
                       ^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:222:24: Error: Expected ';' after this.
  _yController.value = 1.0;
                       ^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:222:3: Error: The name of a constructor must match the name of the enclosing class.
  _yController.value = 1.0;
  ^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:222:24: Error: Expected a class member, but got '1.0'.
  _yController.value = 1.0;
                       ^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:222:27: Error: Expected a class member, but got ';'.
  _yController.value = 1.0;
                          ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:224:27: Error: Expected ')' before this.
  _indexToPosition(index) / MediaQuery
                          ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:223:3: Error: The name of a constructor must match the name of the enclosing class.
  _xController.animateTo(
  ^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:230:24: Error: Non-optional parameters can't have a default value.
Try removing the default value or making the parameter optional.
  Duration(milliseconds: 500) * widget.animationFactor,
                       ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:230:31: Error: Expected ')' before this.
  Duration(milliseconds: 500) * widget.animationFactor,
                              ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:229:3: Error: The name of a constructor must match the name of the enclosing class.
  Future.delayed(
  ^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:236:26: Error: Expected an identifier, but got '0.0'.
  _yController.animateTo(0.0,
                         ^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:237:11: Error: Non-optional parameters can't have a default value.
Try removing the default value or making the parameter optional.
  duration: Duration(milliseconds: 300) * widget.animationFactor);
          ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:236:3: Error: The name of a constructor must match the name of the enclosing class.
  _yController.animateTo(0.0,
  ^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:236:3: Error: '_FluidNavBarState.animateTo' is already declared in this scope.
  _yController.animateTo(0.0,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:223:3: Context: Previous declaration of '_FluidNavBarState.animateTo'.
  _xController.animateTo(
  ^^^^^^^^^^^^^^^^^^^^^^^^...
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:239:3: Error: Expected a class member, but got 'if'.
  if (widget.onChange != null) {
  ^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:239:6: Error: Expected an identifier, but got '('.
  if (widget.onChange != null) {
     ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:239:23: Error: Expected an identifier, but got '!='.
  if (widget.onChange != null) {
                      ^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:239:26: Error: Expected ')' before this.
  if (widget.onChange != null) {
                         ^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:239:7: Error: Type 'widget.onChange' not found.
  if (widget.onChange != null) {
      ^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:218:3: Error: The method '_FluidNavBarState.setState' has fewer positional arguments than those of overridden method 'State.setState'.
  setState(() {
  ^
../../flutter/packages/flutter/lib/src/widgets/framework.dart:1196:8: Context: This is the overridden method ('setState').
  void setState(VoidCallback fn) {
       ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:74:7: Error: The implementation of 'setState' in the non-abstract class '_FluidNavBarState' does not conform to its interface.
class _FluidNavBarState extends State<FluidNavBar>
      ^^^^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/widgets/framework.dart:1196:8: Context: The method 'State.setState' has more required arguments than those of overridden method '_FluidNavBarState.setState'.
  void setState(VoidCallback fn) {
       ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:218:3: Context: This is the overridden method ('setState').
  setState(() {
  ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:69:26: Error: Method not found: '_FluidNavBarState'.
  State createState() => _FluidNavBarState();
                         ^^^^^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:91:15: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
      setState(() {});
              ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:222:22: Error: Expected a function body or '=>'.
Try adding {}.
  _yController.value = 1.0;
                     ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:222:24: Error: Constructors can't have a return type.
Try removing the return type.
  _yController.value = 1.0;
                       ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:237:13: Error: Constant expression expected.
Try inserting 'const'.
  duration: Duration(milliseconds: 300) * widget.animationFactor);
            ^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/fluid_bottom_nav_bar-1.0.1/lib/src/fluid_nav_bar.dart:237:43: Error: Getter not found: 'widget'.
  duration: Duration(milliseconds: 300) * widget.animationFactor);
                                          ^^^^^^
`

**Comment by eric-taix-teads** [comment]
The stack trace is unreadable...
I don't know what happens for you, but clearly this is not an issue of this library. Many people use this version without any issue.

**Comment by eric-taix** [comment]
Did you solve your issue? If yes can you provide more relevant informations how you solved it to help others in cas they encounter the same issue?

**Comment by sarcastic-verma** [comment]
> Did you solve your issue? If yes can you provide more relevant informations how you solved it to help others in cas they encounter the same issue?

Unfortunately, I couldn't solve the issue.

**Comment by eric-taix** [comment]
Did you try `flutter clean`, upgrade to the latest stable version of SDK, flutter and this library?  It seems to be a compilation error on the library code itself

**Comment by sarcastic-verma** [comment]
Yes I did that...it didn't seem to work at that point but I'll do it again just in case.

**Comment by eric-taix** [comment]
Since there is no additional information, I close this problem. Do not hesitate to reopen it if necessary.
