### ISSUE TITLE
Can I use normal icons?

### ISSUE THREAD

**Issue by elias97850** [eric-taix/fluid-nav-bar#9]
For the icons it asks for a path, but I'm just using the default icons that flutter has. Is there a way to change them into a path?

**Comment by tanzilzubair** [comment]
I also have this question.

**Comment by eric-taix-teads** [comment]
Sorry for the delay. I used first SVG to be able to have more complex animation (SVG animation paths) but for now it's not possible due to an issue in the library. 
So yes I think, I can add a way to use normal icons.

**Comment by umaqs** [comment]
I just added this feature please have a look at pr #21

**Comment by eric-taix** [comment]
The PR #21 has been merged and published to pub.dev, enjoy!
Thanks to @umaqs
